export let items = [{
    description: 'Vintage Typewriter to post awesome stories about UI design and webdev.',
    price: '$49.50',
    img: 'img/items/item01.png',
    id: 1,
    quantity: 1,
    tags: 'Entertainment, Toys, Vintage'

},
    {description: 'Lee Pucker design. Leather botinki for handsome designers. Free shipping.',
    price: '$13.95',
    img: 'img/items/item02.png',
    id: 2,
    quantity: 1,
    tags: 'Clothing & Shoes'
},
    {description: 'Timesaving kitten to save months on development. Playful, cute, cheap!',
    price: '$128.99',
    img: 'img/items/item03.png',
    id: 3,
    quantity: 1,
    tags: 'Pets'
},
    {description: 'Plastic useless plugs and tubes for high-fidelity prototyping. Fit & Eat!',
    price: '$12.48',
    img: 'img/items/item04.png',
    id: 4,
    quantity: 1,
    tags: 'Kitchen Accessories'
},
    {description: 'Creativity stimulating lotion. Drink every morning to generate better ideas!',
    price: '$10.75',
    img: 'img/items/item05.png',
    id: 5,
    quantity: 0,
    tags: 'Kitchen Accessories'
},
    {description: 'Prototyping items to create a lot if useless things...',
    price: '$22.00',
    img: 'img/items/item06.png',
    id: 6,
    quantity: 0,
    tags: 'Entertainment, Sport & Lifestyle'
},
    {description: 'John Von Ebalkin SPRING ',
    price: '$80.75',
    img: 'img/items/item07.png',
    id: 7,
    quantity: 0,
    tags: 'Clothing & Shoes'
},
    {description: 'Envelope, Stripes, Pencil and etc. Purchase this kit today and feel OKAY',
    price: '$5.75',
    img: 'img/items/item08.png',
    id: 8,
    quantity: 0,
    tags: 'Entertainment, Sport & Lifestyle'
},
    {description: 'Gabb Phone Plus. The Premium Safe Phone for Kids',
    price: '$199.99',
    img: 'img/items/item09.png',
    id: 9,
    quantity: 0,
    tags: 'Electrical Tools, Entertainment'
},
    {description: 'MP3 Player 32GB with Speaker FM Radio Earphone Portable HiFi Lossless Sound',
    price: '$20.99',
    img: 'img/items/item10.jpg',
    id: 10,
    quantity: 0,
    tags: 'Electrical Tools, Vintage, Music, Entertainment'
},
    {description: 'Scout Backpack Tent Forest With our 2-person backpacking tent, you sleep comfortable wherever you roam',
    price: '$49.99',
    img: 'img/items/item11.png',
    id: 11,
    quantity: 0,
    tags: 'Travel Equipment'
},
    {description: 'LEGO Ideas Home Alone 21330 Building Kit; Buildable Movie Memorabilia',
    price: '$299.95',
    img: 'img/items/item12.png',
    id: 12,
    quantity: 0,
    tags: 'Toys'
},
    {description: 'Graco Baby Carrier Online Shop',
    price: '$65.95',
    img: 'img/items/item13.png',
    id: 13,
    quantity: 0,
    tags: 'Mother Care'
},
    {description: 'Garden Tools You Need to Start a Garden',
    price: '$165.95',
    img: 'img/items/item14.png',
    id: 14,
    quantity: 0,
    tags: 'Growing & Garden'
},
    {description: 'AppleRound Pack of 4 Sports Balls with 1 Pump',
    price: '$90.49',
    img: 'img/items/item15.png',
    id: 15,
    quantity: 0,
    tags: 'Sport & Lifestyle'
},
    {description: '20x50 High Power Military Binoculars',
    price: '$46.49',
    img: 'img/items/item16.png',
    id: 16,
    quantity: 0,
    tags: 'Sport & Lifestyle, Travel Equipment'
}                                                                              
]